language: ruby
rvm:
    - 1.9.3
    - 2.0.0
    - 2.2.4
    - 2.3.0
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-4.8
        - libsnappy-dev
        - realpath
before_install:
    - export CC="gcc-4.8"
    - mkdir deps
    - git clone https://github.com/openvenues/libpostal
    - cd libpostal
    - ./bootstrap.sh
    - ./configure --datadir=$(pwd)/data --prefix=$(realpath $(pwd)/../deps) --bindir=$(realpath $(pwd)/../deps)
    - make install
    - cd ..
script:
    - export CFLAGS=-I$(pwd)/deps/include
    - export LDFLAGS=-L$(pwd)/deps/lib
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/deps/lib
    - bundle exec rake test